#!/bin/sh

DB_USER_DEFAULT=$bamboo_dbUser_default
DB_PASSWORD_DEFAULT=$bamboo_dbPwd_default
DB_HOST_DEFAULT=$bamboo_dbHost_default
DB_NAME_DEFAULT=$bamboo_dbName_default

DB_USER_MAIN=$bamboo_dbUser_main
DB_PASSWORD_MAIN=$bamboo_dbPwd_main
DB_HOST_MAIN=$bamboo_dbHost_main
DB_HOST_MAIN_SLAVE0=$bamboo_dbHost_main_slave0
DB_HOST_MAIN_SLAVE1=$bamboo_dbHost_main_slave1
DB_HOST_MAIN_SLAVE2=$bamboo_dbHost_main_slave2
DB_HOST_MAIN_SLAVE3=$bamboo_dbHost_main_slave3
DB_HOST_MAIN_SLAVE4=$bamboo_dbHost_main_slave4
DB_NAME_MAIN=$bamboo_dbName_main

DB_USER_GLOBAL=$bamboo_dbUser_global
DB_PASSWORD_GLOBAL=$bamboo_dbPwd_global
DB_HOST_GLOBAL=$bamboo_dbHost_global
DB_HOST_GLOBAL_SLAVE0=$bamboo_dbHost_global_slave0
DB_HOST_GLOBAL_SLAVE1=$bamboo_dbHost_global_slave1
DB_HOST_GLOBAL_SLAVE2=$bamboo_dbHost_global_slave2
DB_HOST_GLOBAL_SLAVE3=$bamboo_dbHost_global_slave3
DB_HOST_GLOBAL_SLAVE4=$bamboo_dbHost_global_slave4
DB_NAME_GLOBAL=$bamboo_dbName_global

DB_USER_BANK=$bamboo_dbUser_bank
DB_PASSWORD_BANK=$bamboo_dbPwd_bank
DB_HOST_BANK=$bamboo_dbHost_bank
DB_HOST_BANK_SLAVE0=$bamboo_dbHost_bank_slave0
DB_HOST_BANK_SLAVE1=$bamboo_dbHost_bank_slave1
DB_NAME_BANK=$bamboo_dbName_bank

sed -i "/DATABASE_URL/c\DATABASE_URL=mysql://${DB_USER_DEFAULT}:${DB_PASSWORD_DEFAULT}@${DB_HOST_DEFAULT}/${DB_NAME_DEFAULT}" .env
sed -i "/DATABASE_TEST_URL/c\DATABASE_TEST_URL=//${DB_USER_DEFAULT}:${DB_PASSWORD_DEFAULT}@${DB_HOST_DEFAULT}/${DB_NAME_DEFAULT}_test" .env.test

sed -i "/DATABASE_MAIN_URL_MASTER/c\DATABASE_MAIN_URL_MASTER=mysql://${DB_USER_MAIN}:${DB_PASSWORD_MAIN}@${DB_HOST_MAIN}/${DB_NAME_MAIN}" .env
sed -i "/DATABASE_MAIN_URL_SLAVE0/c\DATABASE_MAIN_URL_SLAVE0=mysql://${DB_USER_MAIN}:${DB_PASSWORD_MAIN}@${DB_HOST_MAIN_SLAVE0}/${DB_NAME_MAIN}" .env
sed -i "/DATABASE_MAIN_URL_SLAVE1/c\DATABASE_MAIN_URL_SLAVE1=mysql://${DB_USER_MAIN}:${DB_PASSWORD_MAIN}@${DB_HOST_MAIN_SLAVE1}/${DB_NAME_MAIN}" .env
sed -i "/DATABASE_MAIN_URL_SLAVE2/c\DATABASE_MAIN_URL_SLAVE2=mysql://${DB_USER_MAIN}:${DB_PASSWORD_MAIN}@${DB_HOST_MAIN_SLAVE2}/${DB_NAME_MAIN}" .env
sed -i "/DATABASE_MAIN_URL_SLAVE3/c\DATABASE_MAIN_URL_SLAVE3=mysql://${DB_USER_MAIN}:${DB_PASSWORD_MAIN}@${DB_HOST_MAIN_SLAVE3}/${DB_NAME_MAIN}" .env
sed -i "/DATABASE_MAIN_URL_SLAVE4/c\DATABASE_MAIN_URL_SLAVE4=mysql://${DB_USER_MAIN}:${DB_PASSWORD_MAIN}@${DB_HOST_MAIN_SLAVE4}/${DB_NAME_MAIN}" .env

sed -i "/DATABASE_GLOBAL_URL_MASTER/c\DATABASE_GLOBAL_URL_MASTER=mysql://${DB_USER_GLOBAL}:${DB_PASSWORD_GLOBAL}@${DB_HOST_GLOBAL}/${DB_NAME_GLOBAL}" .env
sed -i "/DATABASE_GLOBAL_URL_SLAVE0/c\DATABASE_GLOBAL_URL_SLAVE0=mysql://${DB_USER_GLOBAL}:${DB_PASSWORD_GLOBAL}@${DB_HOST_GLOBAL_SLAVE0}/${DB_NAME_GLOBAL}" .env
sed -i "/DATABASE_GLOBAL_URL_SLAVE1/c\DATABASE_GLOBAL_URL_SLAVE1=mysql://${DB_USER_GLOBAL}:${DB_PASSWORD_GLOBAL}@${DB_HOST_GLOBAL_SLAVE1}/${DB_NAME_GLOBAL}" .env
sed -i "/DATABASE_GLOBAL_URL_SLAVE2/c\DATABASE_GLOBAL_URL_SLAVE2=mysql://${DB_USER_GLOBAL}:${DB_PASSWORD_GLOBAL}@${DB_HOST_GLOBAL_SLAVE2}/${DB_NAME_GLOBAL}" .env
sed -i "/DATABASE_GLOBAL_URL_SLAVE3/c\DATABASE_GLOBAL_URL_SLAVE3=mysql://${DB_USER_GLOBAL}:${DB_PASSWORD_GLOBAL}@${DB_HOST_GLOBAL_SLAVE3}/${DB_NAME_GLOBAL}" .env
sed -i "/DATABASE_GLOBAL_URL_SLAVE4/c\DATABASE_GLOBAL_URL_SLAVE4=mysql://${DB_USER_GLOBAL}:${DB_PASSWORD_GLOBAL}@${DB_HOST_GLOBAL_SLAVE4}/${DB_NAME_GLOBAL}" .env

sed -i "/DATABASE_BANK_URL_MAIN/c\DATABASE_BANK_URL_MAIN=mysql://${DB_USER_BANK}:${DB_PASSWORD_BANK}@${DB_HOST_BANK}/${DB_NAME_BANK}" .env
sed -i "/DATABASE_BANK_URL_SLAVE0/c\DATABASE_BANK_URL_SLAVE0=mysql://${DB_USER_BANK}:${DB_PASSWORD_BANK}@${DB_HOST_BANK_SLAVE0}/${DB_NAME_BANK}" .env
sed -i "/DATABASE_BANK_URL_SLAVE1/c\DATABASE_BANK_URL_SLAVE1=mysql://${DB_USER_BANK}:${DB_PASSWORD_BANK}@${DB_HOST_BANK_SLAVE1}/${DB_NAME_BANK}" .env

cp phpunit.xml.dist phpunit.xml

sed -i "s/{DB_USERNAME}:{DB_PASSWORD}/${DB_USER_DEFAULT}:${DB_PASSWORD_DEFAULT}/g" phpunit.xml
sed -i "s/{DB_HOST}/${DB_HOST_DEFAULT}/g" phpunit.xml
sed -i "s/{DB_NAME}/${DB_NAME_DEFAULT}_test/g" phpunit.xml