nelmio_api_doc:
    documentation:
        info:
            title: Omega API
            description: API of Omega
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc|/doc.json$) # Accepts routes under / except /doc
